In [1]:
import numpy as np
import math as m

#numpy::  python lists are slow hence we need numpy
#numpy ::  has same data type of element
#numpy is normally written in c hence more faster

In [2]:
list = [2,3,4]
np.array(list)
list

[2, 3, 4]

In [3]:
print(type(list))

<class 'list'>


In [5]:
arr = np.zeros(10)
print(arr.dtype)
arr

float64


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
np.zeros(10, int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
b = np.zeros((2,3))


In [9]:
b[0][1]

0.0

In [10]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [11]:
a = np.zeros(5)
a[0] = 5
a

array([5., 0., 0., 0., 0.])

In [12]:
a[0]

5.0

In [13]:
#slicing
a[2:4]

array([0., 0.])

In [14]:
a.shape #size

(5,)

In [15]:
b.shape

(2, 3)

In [16]:
d = np.array([[1,2,3],[3,4,5],[3,4,5],[1,2,3]])
d[0]

array([1, 2, 3])

In [17]:
d[:,0] #0th columnand all rows

array([1, 3, 3, 1])

In [18]:


d[0:3,0]

array([1, 3, 3])

In [19]:




d[:,0:2] #all rows but 0 amd 1 column

array([[1, 2],
       [3, 4],
       [3, 4],
       [1, 2]])

In [20]:
#operations
a = np.array([1,2,3])
b = np.array([5,6,7])

c = a + 2
c

array([3, 4, 5])

In [21]:
a + b

array([ 6,  8, 10])

In [22]:
#dimensions need to be same

In [23]:
a * 2

array([2, 4, 6])

In [24]:
a * b

array([ 5, 12, 21])

In [25]:
a.mean()

2.0

In [26]:
a.sum()

6

In [27]:
m.sqrt(a[1])

1.4142135623730951

# Follow this for deeper knowledge

https://docs.scipy.org/doc/numpy/user/quickstart.html